### ISSUE TITLE
Issues with running the command (mainly RELION)

### ISSUE THREAD

**Issue by yilaili** [yilaili/cryohub#7]
- [ ] [Record stdout and stderr files. ](https://github.com/yilaili/cryohub/issues/7#issuecomment-848186060)
- [x] [Automatic output directory generation using RELION's tradition.](https://github.com/yilaili/cryohub/issues/7#issuecomment-848186818)
- [ ] [Run multiple commands with the "Run" button.](https://github.com/yilaili/cryohub/issues/7#issuecomment-848187834)

**Comment by yilaili** [comment]
Add `> run.out 2> run.err` (in the appropriate directory) to the tail of the command running

**Comment by yilaili** [comment]
Currently, all the commands ask the user to type in the output path/name. This issue intends to automatically generate the path with a fixed naming policy.

A typical RELION directory structure is like this (and this project will keep this):
./projectxx
./projectxx/Import
./projectxx/Import/job001
./projectxx/Motioncorr
./projectxx/Motioncorr/job002
./projectxx/Motioncorr/job004
./projectxx/CTF
./projectxx/CTF/job003
./projectxx/CTF/job005
etc.

The index number of each job is automatically created based on which job runs first.
I intend to keep the similar structure, but modify the job index naming a little bit by capturing the inter-relationship between each jobs:
e.g. job004_i002 (job004 uses the outputs from job002 as the input)
job005_i002_i004 (job005 uses the outputs from both job002 and job004 as the inputs)

This requires:

1. The code will loop through the project folder and identify which is the next index to use.
2. The code will read the inputs by the user and identify which jobs are related to the current job.
3. The code will make the required new directory based on what are found in 1 and 2.

**Comment by yilaili** [comment]
Currently, the GUI will parse the inputs into a command to run (for now usually it's a RELION command). We will need to add other commands to run after running the relion command.

For example, the command would be something like:
`relion_import --i ....`
`mrc2png.py -i ....`

And more commands as needed. The command in the following lines are usually fixed, and the input will be inferred from the arguments in the first command.
